# Generated by Django 5.1.4 on 2025-01-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='actualites/')),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('subject', models.CharField(max_length=255, verbose_name='Objet')),
                ('message', models.TextField(verbose_name='Message')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=255, verbose_name='Nom et Prénom')),
                ('email', models.EmailField(default='null', max_length=254, verbose_name='Adresse Email')),
                ('phone', models.CharField(default='null', max_length=15, verbose_name='Numéro de Téléphone')),
                ('cv', models.FileField(null=True, upload_to='postulations/cv/', verbose_name='CV')),
                ('certificat', models.FileField(null=True, upload_to='postulations/certificat/', verbose_name='Certificat de Scolarité')),
                ('message', models.TextField(blank=True, default='null', verbose_name='Message')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='Date de Soumission')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='null', max_length=255, verbose_name='Nom et Prénom')),
                ('email', models.EmailField(default='null', max_length=254, verbose_name='Adresse Email')),
                ('phone', models.CharField(default='null', max_length=15, verbose_name='Numéro de Téléphone')),
                ('cv', models.FileField(null=True, upload_to='postulations/cv/', verbose_name='CV')),
                ('certificat', models.FileField(null=True, upload_to='postulations/certificat/', verbose_name='Certificat de Scolarité')),
                ('message', models.TextField(blank=True, default='null', verbose_name='Message')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, verbose_name='Date de Soumission')),
            ],
            options={
                'verbose_name': 'Stage',
                'verbose_name_plural': 'Stages',
            },
        ),
    ]
