# Generated by Django 5.1.4 on 2025-01-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(default='null', max_length=15, verbose_name='Numéro de Téléphone'),
        ),
    ]
